#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_focus true                                          
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
# You need to do this to stop that pesky gap that is added 
# for polybar
bspc config top_padding 0

exec polybar &
exec xcompmgr -r 0 -o 1 -a &
exec xautolock -time 15 -locker "$HOME/.config/i3/i3lock.sh" &
exec flameshot &
exec xsetroot -cursor_name left_ptr &
exec redshift &
exec mpdas &
exec mpd-discord-rpc &
exec feh --bg-max --bg-fill --bg-center --randomize ~/Pictures/WP/* &
exec xrdb "$HOME/.Xresources" &
exec xmodmap -e "clear lock" &
#exec xmodmap -e "keycode 9 = Caps_Lock NoSymbol Caps_Lock" &
exec xmodmap -e "keycode 66 = Escape NoSymbol Escape" &

